version: "3"

volumes:
  deathmatchpgdata:
  static_volume:

services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./staticfiles:/home/app/staticfiles
  postgres:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - deathmatchpgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
  web:
    depends_on:
      - postgres
    restart: always
    build: .
    image: thatcherthornberry/deathmatch:latest
    command: gunicorn deathmatch.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./staticfiles:/home/app/statifiles